name: publish
on:
  push:
    tags:
      - 'v\d+.*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  publish:
    environment: publish
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/workflows/shared-setup
      with:
        jdk: '11'

    - name: Deploy to clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: bb -ci-clojars-deploy

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bb -ci-github-create-release

    - name: Inform Cljdoc
      run: bb -ci-cljdoc-request-build
